# Generated by Django 4.0.2 on 2022-02-18 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.CharField(blank=True, max_length=200, null=True)),
                ('capa', models.ImageField(blank=True, default='imagens/capa-default.png', null=True, upload_to='')),
                ('editora', models.CharField(blank=True, max_length=200, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
