# Generated by Django 4.0.2 on 2022-02-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusLivrosApp', '0004_alter_livro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, default='capa-default.png', null=True, upload_to='imagens'),
        ),
    ]
