# Generated by Django 4.0.2 on 2022-02-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusLivrosApp', '0006_rename_descricao_livro_resenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
